plugins {
    id 'java-library'
    id 'maven-publish'
}

version = "${craftcreator_version}"
group = 'fr.en0ri4n.craftcreator'

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
}

dependencies {
    // GSON
    implementation 'com.google.code.gson:gson:2.8.9'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}